sudo: false
language: node_js
node_js:
  - "6"
env: MAINRUN=true
before_install:
  - npm config set ca ""
install:
  - npm install && npm install travis-ci
after_success:
  - npm run-script coveralls
  - if [[ $TRAVIS_BRANCH = "master" ]] && [[ $TRAVIS_PULL_REQUEST = "false" ]]; then node trigger-deploy-mn-com.js; fi
  
